imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ContactBundle/Resources/config/services.yml" }
    - { resource: "@SkillsBundle/Resources/config/services.yml" }
    - { resource: "@EducationBundle/Resources/config/services.yml" }
    - { resource: "@SportsBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    assets:
        vendor_css:
            inputs:
                - 'assets/vendor/bootstrap/dist/css/bootstrap.css'
                - 'assets/vendor/bootstrap/dist/css/bootstrap-theme.css'
                - 'assets/vendor/font-awesome/css/font-awesome.css'
        main_css:
            inputs:
                - 'assets/app/css/*.css'
        vendor_js:
            inputs:
                - 'assets/vendor/jquery/dist/jquery.js'
                - 'assets/vendor/angular/angular.min.js'
                - 'assets/vendor/angular-route/angular-route.min.js'
        main_js:
            inputs:
                - 'assets/app/js/app.module.js'

                - 'assets/app/js/core/core.module.js'
                - 'assets/app/js/core/*.js'

                - 'assets/app/js/blocks/router/router.module.js'
                - 'assets/app/js/blocks/router/routerhelper.js'

                - 'assets/app/js/sidebar/sidebar.module.js'
                - 'assets/app/js/sidebar/*.js'

                - 'assets/app/js/contact/contact.module.js'
                - 'assets/app/js/contact/*.js'

                - 'assets/app/js/skills/skills.module.js'
                - 'assets/app/js/skills/*.js'

                - 'assets/app/js/education/education.module.js'
                - 'assets/app/js/education/*.js'
                
                - 'assets/app/js/sports/sports.module.js'
                - 'assets/app/js/sports/*.js'

        angular_tpl:
            inputs:
                - 'assets/app/tpl/contact/*.html'
                - 'assets/app/tpl/skills/*.html'
                - 'assets/app/tpl/education/*.html'
                - 'assets/app/tpl/sports/*.html'
miguel_assetic_angular_js:
    app_name: app