sports:
    resource: "@SportsBundle/Controller/"
    type:     annotation
    prefix:   /

education:
    resource: "@EducationBundle/Controller/"
    type:     annotation
    prefix:   /

skills:
    resource: "@SkillsBundle/Controller/"
    type:     annotation
    prefix:   /

contact:
    resource: "@ContactBundle/Controller/"
    type:     annotation
    prefix:   /