# This is an appspec.yml template file for use with AWS CodeDeploy.
#   http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux
files:
  - source: /site/bin/console
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/bin
  - source: /site/src
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/src
  - source: /site/app
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/app
  - source: /site/var/SymfonyRequirements.php
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/var/
  - source: /site/web/.htaccess
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web
  - source: /site/web/app.php
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web
  - source: /site/web/favicon.ico
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web
  - source: /site/web/robots.txt
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web
  - source: /site/composer.json
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com
  - source: /site/composer.lock
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com
permissions:
  - object: /var/www/vhosts/dev.miguelgonzalezgomez.com/composer.json
    owner: ec2-user
    group: ec2-user
  - object: /var/www/vhosts/dev.miguelgonzalezgomez.com/composer.lock
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root