# This is an appspec.yml template file for use with AWS CodeDeploy.
#   http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux
files:
  - source: /site/src
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/src
  - source: /site/app
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/app
  - source: /site/web/css
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web/css
  - source: /site/web/fonts
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web/fonts
  - source: /site/web/images
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web/images
  - source: /site/web/img
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web/img
  - source: /site/web/js
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web/js
  - source: /site/web/.htaccess
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web
  - source: /site/web/app.php
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web
  - source: /site/web/favicon.ico
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web
  - source: /site/web/robots.txt
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web
  - source: /site/composer.json
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com
  - source: /site/composer.lock
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com
permissions:
  - object: /var/www/vhosts/dev.miguelgonzalezgomez.com/src
    owner: ssh-user
    group: ssh-user
  - object: /var/www/vhosts/dev.miguelgonzalezgomez.com/app
    owner: ssh-user
    group: ssh-user
  - object: /var/www/vhosts/dev.miguelgonzalezgomez.com/web
    owner: www-data
    group: www-data
  - object: /var/www/vhosts/dev.miguelgonzalezgomez.com/composer.json
    owner: ssh-user
    group: ssh-user
  - object: /var/www/vhosts/dev.miguelgonzalezgomez.com/composer.lock
    owner: ssh-user
    group: ssh-user
hooks:
  ApplicationStop:
#    - location:
#      timeout:
#      runas:
#  BeforeInstall:
#    - location:
#      timeout:
#      runas:
  AfterInstall:
    - location: scripts/prepare_environment
      timeout: 300
      runas: ssh-user
#  ApplicationStart:
#    - location: scripts/start_application
#      timeout: 300
#      runas: root
#  ValidateService:
#    - location:
#      timeout:
#      runas: