# This is an appspec.yml template file for use with AWS CodeDeploy.
#   http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux
files:
  - source: /site/bin/console
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/bin
  - source: /site/src
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/src
  - source: /site/app
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/app
  - source: /site/var/SymfonyRequirements.php
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/var/
#  - source: /site/web/css
#    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web/css
#  - source: /site/web/fonts
#    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web/fonts
#  - source: /site/web/images
#    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web/images
#  - source: /site/web/img
#    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web/img
#  - source: /site/web/js
#    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web/js
  - source: /site/web/.htaccess
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web
  - source: /site/web/app.php
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web
  - source: /site/web/favicon.ico
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web
  - source: /site/web/robots.txt
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com/web
  - source: /site/composer.json
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com
  - source: /site/composer.lock
    destination: /var/www/vhosts/dev.miguelgonzalezgomez.com
permissions:
  - object: /var/www/vhosts/dev.miguelgonzalezgomez.com/bin/console
    owner: ec2-user
    group: ec2-user
#  - object: /var/www/vhosts/dev.miguelgonzalezgomez.com/app
#    owner: ec2-user
#    group: ec2-user
#  - object: /var/www/vhosts/dev.miguelgonzalezgomez.com/web
#    owner: ec2-user
#    group: ec2-user
#  - object: /var/www/vhosts/dev.miguelgonzalezgomez.com/var
#    owner: ec2-user
#    group: ec2-user
  - object: /var/www/vhosts/dev.miguelgonzalezgomez.com/composer.json
    owner: ec2-user
    group: ec2-user
  - object: /var/www/vhosts/dev.miguelgonzalezgomez.com/composer.lock
    owner: ec2-user
    group: ec2-user
hooks:
#  ApplicationStop:
#    - location:
#      timeout:
#      runas:
#  BeforeInstall:
#    - location:
#      timeout:
#      runas:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/clear_cache
      timeout: 300
      runas: ec2-user
#  ValidateService:
#    - location:
#      timeout:
#      runas: